model = {
    "keys": {
        "Ab Major": {
            "name": "Ab Major",
            "chords": [
                "Ab Major",
                "Bb minor",
                "C minor",
                "Db Major",
                "Eb Major",
                "F minor",
            ],
        },
        "Ab minor": {
            "name": "Ab minor",
            "chords": [
                "Ab minor",
                "Cb Major",
                "Db minor",
                "Eb minor",
                "Fb Major",
                "Gb Major",
            ],
        },
        "A Major": {
            "name": "A Major",
            "chords": [
                "A Major",
                "B minor",
                "C# minor",
                "D Major",
                "E Major",
                "F# minor",
            ],
        },
        "A minor": {
            "name": "A minor",
            "chords": [
                "A minor",
                "C Major",
                "D minor",
                "E minor",
                "F Major",
                "G Major",
            ],
        },
        "A# Major": {
            "name": "A# Major",
            "chords": [
                "A# Major",
                "B# minor",
                "C## minor",
                "D# Major",
                "E# Major",
                "F## minor",
            ],
        },
        "A# minor": {
            "name": "A# minor",
            "chords": [
                "A# minor",
                "C# Major",
                "D# minor",
                "E# minor",
                "F# Major",
                "G# Major",
            ],
        },
        "Bb Major": {
            "name": "Bb Major",
            "chords": [
                "Bb Major",
                "C minor",
                "D minor",
                "Eb Major",
                "F Major",
                "G minor",
            ],
        },
        "Bb minor": {
            "name": "Bb minor",
            "chords": [
                "Bb minor",
                "Db Major",
                "Eb minor",
                "F minor",
                "Gb Major",
                "Ab Major",
            ],
        },
        "B Major": {
            "name": "B Major",
            "chords": [
                "B Major",
                "C# minor",
                "D# minor",
                "E Major",
                "F# Major",
                "G# minor",
            ],
        },
        "B minor": {
            "name": "B minor",
            "chords": [
                "B minor",
                "D Major",
                "E minor",
                "F# minor",
                "G Major",
                "A Major",
            ],
        },
        "B# Major": {
            "name": "B# Major",
            "chords": [
                "B# Major",
                "C## minor",
                "D## minor",
                "E# Major",
                "F## Major",
                "G## minor",
            ],
        },
        "B# minor": {
            "name": "B# minor",
            "chords": [
                "B# minor",
                "D# Major",
                "E# minor",
                "F## minor",
                "G# Major",
                "A# Major",
            ],
        },
        "Cb Major": {
            "name": "Cb Major",
            "chords": [
                "Cb Major",
                "Db minor",
                "Eb minor",
                "Fb Major",
                "Gb Major",
                "Ab minor",
            ],
        },
        "Cb minor": {
            "name": "Cb minor",
            "chords": [
                "Cb minor",
                "Ebb Major",
                "Fb minor",
                "Gb minor",
                "Abb Major",
                "Bbb Major",
            ],
        },
        "C Major": {
            "name": "C Major",
            "chords": [
                "C Major",
                "D minor",
                "E minor",
                "F Major",
                "G Major",
                "A minor",
            ],
        },
        "C minor": {
            "name": "C minor",
            "chords": [
                "C minor",
                "Eb Major",
                "F minor",
                "G minor",
                "Ab Major",
                "Bb Major",
            ],
        },
        "C# Major": {
            "name": "C# Major",
            "chords": [
                "C# Major",
                "D# minor",
                "E# minor",
                "F# Major",
                "G# Major",
                "A# minor",
            ],
        },
        "C# minor": {
            "name": "C# minor",
            "chords": [
                "C# minor",
                "E Major",
                "F# minor",
                "G# minor",
                "A Major",
                "B Major",
            ],
        },
        "Db Major": {
            "name": "Db Major",
            "chords": [
                "Db Major",
                "Eb minor",
                " F minor",
                "Gb Major",
                "Ab Major",
                "Bb minor",
            ],
        },
        "Db minor": {
            "name": "Db minor",
            "chords": [
                "Db minor",
                "Fb Major",
                "Gb minor",
                "Ab minor",
                "Bbb Major",
                "Cb Major",
            ],
        },
        "D Major": {
            "name": "D Major",
            "chords": [
                "D Major",
                "E minor",
                "F# minor",
                "G Major",
                "A Major",
                "B minor",
            ],
        },
        "D minor": {
            "name": "D minor",
            "chords": [
                "D minor",
                "F Major",
                "G minor",
                "A minor",
                "Bb Major",
                "C Major",
            ],
        },
        "D# Major": {
            "name": "D# Major",
            "chords": [
                "D# Major",
                "E# minor",
                "F## minor",
                "G# Major",
                "A# Major",
                "B# minor",
            ],
        },
        "D# minor": {
            "name": "D# minor",
            "chords": [
                "D# minor",
                "F# Major",
                "G# minor",
                "A# minor",
                "B Major",
                "C# Major",
            ],
        },
        "Eb Major": {
            "name": "Eb Major",
            "chords": [
                "Eb Major",
                "F minor",
                "G minor",
                "Ab Major",
                "Bb Major",
                "C minor",
            ],
        },
        "Eb minor": {
            "name": "Eb minor",
            "chords": [
                "Eb minor",
                "Gb Major",
                "Ab minor",
                "Bb minor",
                "Cb Major",
                "Db Major",
            ],
        },
        "E Major": {
            "name": "E Major",
            "chords": [
                "E Major",
                "F# minor",
                "G# minor",
                "A Major",
                "B Major",
                "C# minor",
            ],
        },
        "E minor": {
            "name": "E minor",
            "chords": [
                "E minor",
                "G Major",
                "A minor",
                "B minor",
                "C Major",
                "D Major",
            ],
        },
        "E# Major": {
            "name": "E# Major",
            "chords": [
                "E# Major",
                "F## minor",
                "G## minor",
                "A# Major",
                "B# Major",
                "C## minor",
            ],
        },
        "E# minor": {
            "name": "E# minor",
            "chords": [
                "E# minor",
                "G# Major",
                "A# minor",
                "B# minor",
                "C# Major",
                "D# Major",
            ],
        },
        "Fb Major": {
            "name": "Fb Major",
            "chords": [
                "Fb Major",
                "Gb minor",
                "Ab minor",
                "Bbb Major",
                "Cb Major",
                "Db minor",
            ],
        },
        "Fb minor": {
            "name": "Fb minor",
            "chords": [
                "Fb minor",
                "Abb Major",
                "Bbb minor",
                "Cb minor",
                "Dbb Major",
                "Ebb Major",
            ],
        },
        "F Major": {
            "name": "F Major",
            "chords": [
                "F Major",
                "G minor",
                "A minor",
                "Bb Major",
                "C Major",
                "D minor",
            ],
        },
        "F minor": {
            "name": "F minor",
            "chords": [
                "F minor",
                "Ab Major",
                "Bb minor",
                "C minor",
                "Db Major",
                "Eb Major",
            ],
        },
        "F# Major": {
            "name": "F# Major",
            "chords": [
                "F# Major",
                "G# minor",
                "A# minor",
                "Bb Major",
                "C# Major",
                "D# minor",
            ],
        },
        "F# minor": {
            "name": "F# minor",
            "chords": [
                "F# minor",
                "A Major",
                "B minor",
                "C# minor",
                "D Major",
                "E Major",
            ],
        },
        "Gb Major": {
            "name": "Gb Major",
            "chords": [
                "Gb Major",
                "Ab minor",
                "Bb minor",
                "B Major",
                "Db Major",
                "Eb minor",
            ],
        },
        "Gb minor": {
            "name": "Gb minor",
            "chords": [
                "Gb minor",
                "Bbb Major",
                "Cb minor",
                "Db minor",
                "Ebb Major",
                "Fb Major",
            ],
        },
        "G Major": {
            "name": "G Major",
            "chords": [
                "G Major",
                "A minor",
                "B minor",
                "C Major",
                "D Major",
                "E minor",
            ],
        },
        "G minor": {
            "name": "G minor",
            "chords": [
                "G minor",
                "Bb Major",
                "C minor",
                "D minor",
                "Eb Major",
                "F Major",
            ],
        },
        "G# Major": {
            "name": "G# Major",
            "chords": [
                "G# Major",
                "A# minor",
                "B# minor",
                "C# Major",
                "D# Major",
                "E# minor",
            ],
        },
        "G# minor": {
            "name": "G# minor",
            "chords": [
                "G# minor",
                "B Major",
                "C# minor",
                "Eb minor",
                "E Major",
                "Gb Major",
            ],
        },
    },
    "chords": {
        "Abb Major": {"name": "Abb Major", "notes": ["G", "B", "D"]},
        "Ab Major": {"name": "Ab Major", "notes": ["G#", "C", "D#"]},
        "Ab minor": {"name": "Ab minor", "notes": ["G#", "B", "D#"]},
        "A Major": {"name": "A Major", "notes": ["A", "C#", "E"]},
        "A minor": {"name": "A minor", "notes": ["A", "C", "E"]},
        "A# Major": {"name": "A# Major", "notes": ["A#", "D", "F"]},
        "A# minor": {"name": "A# minor", "notes": ["A#", "C#", "F"]},
        "Bbb Major": {"name": "Bbb Major", "notes": ["A", "C#", "E"]},
        "Bbb minor": {"name": "Bbb minor", "notes": ["A", "C", "E"]},
        "Bb Major": {"name": "Bb Major", "notes": ["A#", "D", "F"]},
        "Bb minor": {"name": "Bb minor", "notes": ["A#", "C#", "F"]},
        "B Major": {"name": "B Major", "notes": ["B", "D#", "F#"]},
        "B minor": {"name": "B minor", "notes": ["B", "D", "F#"]},
        "B# Major": {"name": "B# Major", "notes": ["C", "E", "G"]},
        "B# minor": {"name": "B# minor", "notes": ["C", "D#", "G"]},
        "Cb Major": {"name": "Cb Major", "notes": ["B", "D#", "F#"]},
        "Cb minor": {"name": "Cb minor", "notes": ["B", "D", "F#"]},
        "C Major": {"name": "C Major", "notes": ["C", "E", "G"]},
        "C minor": {"name": "C minor", "notes": ["C", "D#", "G"]},
        "C# Major": {"name": "C# Major", "notes": ["C#", "F", "G#"]},
        "C# minor": {"name": "C# minor", "notes": ["C#", "E", "G#"]},
        "C## minor": {"name": "C## minor", "notes": ["D", "F", "A"]},
        "Dbb Major": {"name": "Dbb Major", "notes": ["C", "E", "G"]},
        "Db Major": {"name": "Db Major", "notes": ["C#", "F", "G#"]},
        "Db minor": {"name": "Db minor", "notes": ["C#", "E", "G#"]},
        "D Major": {"name": "D Major", "notes": ["D", "F#", "A"]},
        "D minor": {"name": "D minor", "notes": ["D", "F", "A"]},
        "D# Major": {"name": "D# Major", "notes": ["D#", "G", "A#"]},
        "D# minor": {"name": "D# minor", "notes": ["D#", "F#", "A#"]},
        "D## minor": {"name": "D## minor", "notes": ["E", "G", "B"]},
        "Ebb Major": {"name": "Ebb Major", "notes": ["D", "F#", "A"]},
        "Eb Major": {"name": "Eb Major", "notes": ["D#", "G", "A#"]},
        "Eb minor": {"name": "Eb minor", "notes": ["D#", "F#", "A#"]},
        "E Major": {"name": "E Major", "notes": ["E", "G#", "B"]},
        "E minor": {"name": "E minor", "notes": ["E", "G", "B"]},
        "E# Major": {"name": "E# Major", "notes": ["F", "A", "C"]},
        "E# minor": {"name": "E# minor", "notes": ["F", "G#", "C"]},
        "Fb Major": {"name": "Fb Major", "notes": ["E", "G#", "B"]},
        "Fb minor": {"name": "Fb minor", "notes": ["E", "G", "B"]},
        "F Major": {"name": "F Major", "notes": ["F", "A", "C"]},
        "F minor": {"name": "F minor", "notes": ["F", "G#", "C"]},
        "F# Major": {"name": "F# Major", "notes": ["F#", "A#", "C#"]},
        "F# minor": {"name": "F# minor", "notes": ["F#", "A", "C#"]},
        "F## Major": {"name": "F## Major", "notes": ["G", "B", "D"]},
        "F## minor": {"name": "F## minor", "notes": ["G", "A#", "D"]},
        "Gb Major": {"name": "Gb Major", "notes": ["F#", "A#", "C#"]},
        "Gb minor": {"name": "Gb minor", "notes": ["F#", "A", "C#"]},
        "G Major": {"name": "G Major", "notes": ["G", "B", "D"]},
        "G minor": {"name": "G minor", "notes": ["G", "A#", "D"]},
        "G# Major": {"name": "G# Major", "notes": ["G#", "C", "D#"]},
        "G# minor": {"name": "G# minor", "notes": ["G#", "B", "D#"]},
        "G## minor": {"name": "G## minor", "notes": ["A", "C", "E"]},
    },
    "pitches": {
        "A": {"name": "A", "note_numbers": [33, 45, 57], "base_frequency": 55.00},
        "A#": {"name": "A#", "note_numbers": [34, 46, 58], "base_frequency": 58.27},
        "B": {"name": "B", "note_numbers": [35, 47, 59], "base_frequency": 61.74},
        "C": {"name": "C", "note_numbers": [36, 48, 60], "base_frequency": 65.41},
        "C#": {"name": "C#", "note_numbers": [37, 49, 61], "base_frequency": 69.30},
        "D": {"name": "D", "note_numbers": [38, 50, 62], "base_frequency": 73.42},
        "D#": {"name": "D#", "note_numbers": [39, 51, 63], "base_frequency": 77.78},
        "E": {"name": "E", "note_numbers": [40, 52, 64], "base_frequency": 82.41},
        "F": {"name": "F", "note_numbers": [41, 53, 65], "base_frequency": 87.31},
        "F#": {"name": "F#", "note_numbers": [42, 54, 66], "base_frequency": 92.50},
        "G": {"name": "G", "note_numbers": [43, 55, 67], "base_frequency": 98.00},
        "G#": {"name": "G#", "note_numbers": [44, 56, 68], "base_frequency": 103.83},
    },
}
