name: api

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Github Action"
        uses: actions/checkout@master

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Install dependencies"
        run: pip install -r api/requirements.txt --user

      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v2
        with:
          app-name: node-rn
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
