name: api

on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/api.yaml"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements-dev.txt

      - name: "Run black"
        run: |
          black --check api

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

      # - name: "Login via Azure CLI"
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Functions
        uses: azure/functions-action@v2
        with:
          app-name: t-arlah-harmonizer
          publish-profile: ${{ secrets.AZURE_FUNCTIONS_PUBLIC_PROFILE }}
          package: api
